apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: external-dns-cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.cloudflare.keyVault.name | quote }}
    cloudName: "{{ .Values.cloudflare.keyVault.cloudName | default \"AzurePublicCloud\" }}"
    objects: |
      array:
        - |
          objectName: cloudflare-api-token
          objectType: secret
          objectAlias: cloudflare-api-token
    tenantId: {{ .Values.cloudflare.keyVault.tenantId | quote }}
  secretObjects:
    - secretName: cloudflare-api-token
      type: Opaque
      data:
        - objectName: cloudflare-api-token
          key: api-token