apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test-certificate
  namespace: nginx-test
spec:
  secretName: nginx-test-tls # The name of the K8s Secret Cert-Manager will create/update
  issuerRef:
    name: letsencrypt-prod # !!! REPLACE with your actual issuer name !!!
    kind: ClusterIssuer # Use ClusterIssuer if it's defined cluster-wide
  dnsNames:
  - nginx-test.everythingascode.dev # !!! REPLACE with your desired subdomain !!!