apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3 # Using a specific version for stability
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: welcome-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-react-config
      - name: welcome-content
        configMap:
          name: nginx-welcome-page
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP # Only needs to be reachable within the cluster by Traefik
  selector:
    app: nginx-test # Selects pods from the deployment above
  ports:
  - protocol: TCP
    port: 80       # Port the service listens on
    targetPort: 80 # Port the nginx container listens on