apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      initContainers:
      - name: git-clone-build
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Install git
            apk add --no-cache git && \
            # Clone the repository
            git clone https://github.com/sanveld/cloud-builder-canvas.git /app && \
            # Navigate to project directory
            cd /app && \
            # Install dependencies
            npm ci && \
            # Build the project
            npm run build && \
            # Copy build files to the shared volume
            cp -r build/* /usr/share/nginx/html/
        volumeMounts:
        - name: build-output
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.25.3 # Using a specific version for stability
        ports:
        - containerPort: 80
        volumeMounts:
        - name: build-output
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: build-output
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-react-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-service
  namespace: nginx-test
  labels:
    app: nginx-test
spec:
  type: ClusterIP # Only needs to be reachable within the cluster by Traefik
  selector:
    app: nginx-test # Selects pods from the deployment above
  ports:
  - protocol: TCP
    port: 80       # Port the service listens on
    targetPort: 80 # Port the nginx container listens on