apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-welcome-page
  namespace: nginx-test
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Everything as Code - Welcome</title>
        <style>
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background-color: #f7f9fc;
                color: #333;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
            }
            .container {
                max-width: 800px;
                background-color: white;
                border-radius: 8px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                padding: 40px;
                text-align: center;
                margin: 20px;
            }
            h1 {
                color: #2563eb;
                font-size: 2.5rem;
                margin-bottom: 20px;
            }
            .success-icon {
                color: #10b981;
                font-size: 4rem;
                margin-bottom: 20px;
            }
            p {
                font-size: 1.2rem;
                color: #4b5563;
                margin-bottom: 30px;
            }
            .current-date {
                font-size: 1rem;
                color: #6b7280;
                margin-top: 30px;
            }
            .badge {
                display: inline-block;
                background-color: #dbeafe;
                color: #2563eb;
                padding: 8px 16px;
                border-radius: 20px;
                font-weight: 600;
                margin: 10px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="success-icon">✓</div>
            <h1>Welcome to everythingascode.dev</h1>
            <p>You've successfully reached the Everything as Code platform.</p>
            
            <div>
                <span class="badge">Infrastructure as Code</span>
                <span class="badge">GitOps</span>
                <span class="badge">Kubernetes</span>
                <span class="badge">Azure</span>
            </div>
            
            <p>This page confirms that your nginx server is properly configured with TLS and your domain is correctly pointing to this service.</p>
            
            <div class="current-date">
                <script>
                    document.write(new Date().toLocaleDateString('en-US', { 
                        weekday: 'long', 
                        year: 'numeric', 
                        month: 'long', 
                        day: 'numeric' 
                    }));
                </script>
            </div>
        </div>
    </body>
    </html>
