apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-welcome-page
  namespace: nginx-test
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Everything as Code - Welcome</title>
        <style>
            * {
                box-sizing: border-box;
            }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                background-color: #f7f9fc;
                color: #333;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                -webkit-text-size-adjust: 100%;
                -webkit-font-smoothing: antialiased;
            }
            .container {
                width: 90%;
                max-width: 800px;
                background-color: white;
                border-radius: 8px;
                box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
                padding: 5%;
                text-align: center;
                margin: 10px;
            }
            h1 {
                color: #2563eb;
                font-size: clamp(1.5rem, 5vw, 2.5rem);
                margin-bottom: 20px;
                word-wrap: break-word;
            }
            .success-icon {
                color: #10b981;
                font-size: clamp(3rem, 10vw, 4rem);
                margin-bottom: 20px;
            }
            p {
                font-size: clamp(1rem, 3vw, 1.2rem);
                color: #4b5563;
                margin-bottom: 30px;
                padding: 0 5px;
            }
            .current-date {
                font-size: clamp(0.8rem, 2.5vw, 1rem);
                color: #6b7280;
                margin-top: 30px;
            }
            .badges-container {
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                gap: 10px;
                margin: 0 auto 20px auto;
            }
            .badge {
                display: inline-block;
                background-color: #dbeafe;
                color: #2563eb;
                padding: 8px 12px;
                border-radius: 20px;
                font-weight: 600;
                font-size: clamp(0.7rem, 2.5vw, 0.9rem);
                white-space: nowrap;
            }
            @media (max-width: 480px) {
                .container {
                    padding: 25px 15px;
                    width: 95%;
                    margin: 5px;
                }
                .badge {
                    padding: 6px 10px;
                    margin: 4px 2px;
                }
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="success-icon">✓</div>
            <h1>Welcome to everythingascode.dev</h1>
            <p>You've successfully reached the Everything as Code platform.</p>
            
            <div class="badges-container">
                <span class="badge">Infrastructure as Code</span>
                <span class="badge">GitOps</span>
                <span class="badge">Kubernetes</span>
                <span class="badge">Azure</span>
            </div>
            
            <p>This page confirms that your nginx server is properly configured with TLS and your domain is correctly pointing to this service.</p>
            
            <div class="current-date">
                <script>
                    document.write(new Date().toLocaleDateString('en-US', { 
                        weekday: 'long', 
                        year: 'numeric', 
                        month: 'long', 
                        day: 'numeric' 
                    }));
                </script>
            </div>
        </div>
    </body>
    </html>
