apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-welcome-page
  namespace: nginx-test
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>DevPlatform0 - Internal Developer Platform</title>
        <style>
            :root {
                --primary-color: #3b82f6;
                --secondary-color: #10b981;
                --accent-color: #6366f1;
                --text-color: #334155;
                --bg-color: #f8fafc;
                --card-bg: #ffffff;
                --header-gradient: linear-gradient(135deg, #3b82f6 0%, #6366f1 100%);
            }
            * {
                box-sizing: border-box;
                margin: 0;
                padding: 0;
            }
            body {
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                background-color: var(--bg-color);
                color: var(--text-color);
                line-height: 1.6;
                -webkit-text-size-adjust: 100%;
                -webkit-font-smoothing: antialiased;
            }
            header {
                background: var(--header-gradient);
                color: white;
                padding: 5rem 1rem;
                text-align: center;
            }
            .container {
                width: 90%;
                max-width: 1200px;
                margin: 0 auto;
                padding: 2rem 0;
            }
            section {
                margin: 4rem 0;
            }
            h1 {
                font-size: clamp(2rem, 5vw, 3.5rem);
                margin-bottom: 1rem;
                font-weight: 800;
            }
            h2 {
                font-size: clamp(1.5rem, 4vw, 2.5rem);
                margin-bottom: 1.5rem;
                color: var(--primary-color);
                text-align: center;
            }
            h3 {
                font-size: clamp(1.2rem, 3vw, 1.8rem);
                margin-bottom: 1rem;
                color: var(--text-color);
            }
            p {
                font-size: clamp(1rem, 2vw, 1.1rem);
                margin-bottom: 1.5rem;
                max-width: 800px;
                margin-left: auto;
                margin-right: auto;
            }
            .header-subtitle {
                font-size: clamp(1.1rem, 3vw, 1.3rem);
                max-width: 700px;
                margin: 1rem auto 2rem;
            }
            .logo {
                font-size: 2.5rem;
                font-weight: 900;
                margin-bottom: 2rem;
                letter-spacing: -1px;
            }
            .github-link {
                display: inline-block;
                background-color: rgba(255, 255, 255, 0.2);
                color: white;
                padding: 0.8rem 1.5rem;
                border-radius: 50px;
                text-decoration: none;
                font-weight: 600;
                transition: all 0.3s ease;
                margin-top: 1rem;
            }
            .github-link:hover {
                background-color: rgba(255, 255, 255, 0.3);
                transform: translateY(-2px);
            }
            .tech-grid {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
                gap: 2rem;
                margin: 3rem 0;
            }
            .tech-card {
                background: var(--card-bg);
                border-radius: 12px;
                box-shadow: 0 10px 25px rgba(0, 0, 0, 0.05);
                padding: 2rem;
                transition: all 0.3s ease;
                text-align: center;
            }
            .tech-card:hover {
                transform: translateY(-5px);
                box-shadow: 0 15px 30px rgba(0, 0, 0, 0.1);
            }
            .tech-icon {
                font-size: 2.5rem;
                margin-bottom: 1rem;
                color: var(--primary-color);
            }
            .features {
                text-align: center;
                margin: 4rem 0;
            }
            .feature-list {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
                gap: 2rem;
                margin: 3rem 0;
            }
            .feature-item {
                background-color: var(--card-bg);
                padding: 2rem;
                border-radius: 12px;
                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.05);
                text-align: left;
            }
            .feature-icon {
                display: inline-block;
                background-color: rgba(99, 102, 241, 0.1);
                color: var(--accent-color);
                padding: 1rem;
                border-radius: 12px;
                margin-bottom: 1.5rem;
                font-size: 1.5rem;
            }
            .cta-section {
                background: var(--header-gradient);
                color: white;
                padding: 4rem 1rem;
                text-align: center;
                border-radius: 12px;
                margin: 4rem 0;
            }
            .cta-btn {
                display: inline-block;
                background-color: white;
                color: var(--primary-color);
                padding: 0.8rem 2rem;
                border-radius: 50px;
                text-decoration: none;
                font-weight: 600;
                transition: all 0.3s ease;
                margin-top: 1.5rem;
                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
            }
            .cta-btn:hover {
                transform: translateY(-3px);
                box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);
            }
            footer {
                background-color: #1e293b;
                color: white;
                text-align: center;
                padding: 2rem 0;
                margin-top: 4rem;
            }
            .tech-logo {
                height: 50px;
                width: auto;
                margin-bottom: 1.5rem;
            }
            .demo-info {
                background-color: rgba(16, 185, 129, 0.1);
                border-left: 4px solid var(--secondary-color);
                padding: 1.5rem;
                margin: 2rem auto;
                max-width: 800px;
                border-radius: 0 8px 8px 0;
            }
            .demo-badge {
                display: inline-block;
                background-color: var(--secondary-color);
                color: white;
                padding: 0.3rem 1rem;
                border-radius: 50px;
                font-size: 0.9rem;
                font-weight: 600;
                margin-bottom: 1rem;
            }
            .current-date {
                font-size: 0.9rem;
                color: rgba(255, 255, 255, 0.8);
                margin-top: 1.5rem;
            }
            @media (max-width: 768px) {
                .tech-grid, .feature-list {
                    grid-template-columns: 1fr;
                }
            }
            /* Animations */
            @keyframes fadeIn {
                from { opacity: 0; transform: translateY(20px); }
                to { opacity: 1; transform: translateY(0); }
            }
            .animated {
                animation: fadeIn 0.5s ease-out forwards;
            }
            .icon-pulse {
                display: inline-block;
                animation: pulse 2s infinite;
            }
            @keyframes pulse {
                0% { transform: scale(1); }
                50% { transform: scale(1.1); }
                100% { transform: scale(1); }
            }
        </style>
    </head>
    <body>
        <header>
            <div class="container">
                <div class="logo">DevPlatform0</div>
                <h1>Internal Developer Platform</h1>
                <p class="header-subtitle">A complete, code-driven developer platform that can be deployed and destroyed on-demand for demos and testing</p>
                <a href="https://github.com/yourusername/devplatform" class="github-link">
                    View on GitHub ↗
                </a>
                <div class="current-date">
                    <script>
                        document.write("Last updated: " + new Date().toLocaleDateString('en-US', { 
                            weekday: 'long', 
                            year: 'numeric', 
                            month: 'long', 
                            day: 'numeric' 
                        }));
                    </script>
                </div>
            </div>
        </header>

        <div class="container">
            <section class="animated">
                <h2>Your Complete Developer Platform</h2>
                <p>DevPlatform0 is an integrated platform that combines the best tools and practices for modern cloud-native development. 
                Everything is defined as code and stored in a GitHub repository, allowing fast setup and teardown of complete environments.</p>
                
                <div class="demo-info">
                    <span class="demo-badge">Demo Environment</span>
                    <h3>On-Demand Platform</h3>
                    <p>This entire environment can be provisioned or deprovisioned with a few commands, making it perfect for demos, testing, and development purposes.</p>
                </div>
            </section>

            <section class="tech-grid animated">
                <div class="tech-card">
                    <div class="tech-icon">🔄</div>
                    <h3>Azure Kubernetes Service (AKS)</h3>
                    <p>Enterprise-grade Kubernetes service with automated updates and scaling</p>
                </div>

                <div class="tech-card">
                    <div class="tech-icon">🏗️</div>
                    <h3>Terraform</h3>
                    <p>Infrastructure as Code for provisioning and managing cloud infrastructure</p>
                </div>

                <div class="tech-card">
                    <div class="tech-icon">🚢</div>
                    <h3>ArgoCD</h3>
                    <p>GitOps continuous delivery tool for Kubernetes</p>
                </div>

                <div class="tech-card">
                    <div class="tech-icon">🎭</div>
                    <h3>Backstage</h3>
                    <p>Developer portal for building and managing internal developer platforms</p>
                </div>

                <div class="tech-card">
                    <div class="tech-icon">✈️</div>
                    <h3>Crossplane</h3>
                    <p>Cloud native control plane with powerful resource composition capabilities</p>
                </div>

                <div class="tech-card">
                    <div class="tech-icon">🔄</div>
                    <h3>GitOps</h3>
                    <p>Declarative infrastructure and applications defined in Git repositories</p>
                </div>
            </section>

            <section class="features">
                <h2>Platform Features</h2>
                <div class="feature-list">
                    <div class="feature-item">
                        <span class="feature-icon">🔄</span>
                        <h3>Everything as Code</h3>
                        <p>Infrastructure, applications, and configurations defined as code in Git</p>
                    </div>
                    
                    <div class="feature-item">
                        <span class="feature-icon">🚀</span>
                        <h3>Instant Deployment</h3>
                        <p>Spin up complete environments with minimal effort</p>
                    </div>
                    
                    <div class="feature-item">
                        <span class="feature-icon">💰</span>
                        <h3>Cost Effective</h3>
                        <p>Deploy for demos and tear down when not needed to save costs</p>
                    </div>
                    
                    <div class="feature-item">
                        <span class="feature-icon">📊</span>
                        <h3>Self-service Resources</h3>
                        <p>Developers can provision resources through code and templates</p>
                    </div>
                    
                    <div class="feature-item">
                        <span class="feature-icon">🛠️</span>
                        <h3>Integrated Toolchain</h3>
                        <p>Best-in-class tools working together seamlessly</p>
                    </div>
                    
                    <div class="feature-item">
                        <span class="feature-icon">🔐</span>
                        <h3>Secure by Default</h3>
                        <p>Security practices and configurations built in</p>
                    </div>
                </div>
            </section>

            <section class="cta-section animated">
                <h2>Get Started with DevPlatform0</h2>
                <p>Deploy your own instance of DevPlatform0 from the GitHub repository for demos, development, or production use.</p>
                <a href="https://github.com/yourusername/devplatform" class="cta-btn icon-pulse">Clone & Deploy ↗</a>
            </section>
            
            <section class="animated">
                <h2>How It Works</h2>
                <p>DevPlatform0 uses Terraform to provision Azure infrastructure including AKS clusters. ArgoCD deploys and manages applications through GitOps practices. Crossplane extends Kubernetes with custom resources for cloud services, while Backstage provides a developer portal experience for teams.</p>
                <p>All components are designed to work together seamlessly, providing a complete platform experience that can be spun up or down for demo purposes.</p>
            </section>
        </div>

        <footer>
            <div class="container">
                <p>DevPlatform0 - Everything as Code</p>
            </div>
        </footer>
    </body>
    </html>
