apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: external-secrets
spec:
  provider:
    azurekv:
      tenantId: "REPLACE_WITH_TENANT_ID"  # Your Azure tenant ID
      vaultUrl: "https://REPLACE_WITH_KEYVAULT_NAME.vault.azure.net"  # Your KeyVault URL
      serviceAccountRef:
        name: external-secrets  # Must match the service account name