apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_CLIENT_ID"  # Replace with external-secrets managed identity client ID
    azure.workload.identity/tenant-id: "REPLACE_WITH_TENANT_ID"  # Replace with your Azure tenant ID