apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns  # Assuming external-dns will use this, create namespace first
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: azure-keyvault
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api-token  # This matches your KeyVault secret name