apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.9.5 # Check for latest version
    helm:
      releaseName: external-secrets
      values:
        serviceAccount:
          create: true
          name: external-secrets
          annotations:
            azure.workload.identity/client-id: "ad5768e3-3e19-48be-aaec-05391395f77d" # Replace with your ID from terraform output
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
