apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    targetRevision: main
    path: platform-apps/backstage
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: ingress.host
          value: backstage.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true