apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.13
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        # Enable Azure provider in the External Secrets Operator
        provider:
          azure:
            enabled: true
            
        # Define SecretStore configuration
        customResources:
          secretStores:
            - apiVersion: external-secrets.io/v1beta1
              kind: ClusterSecretStore
              metadata:
                name: azure-keyvault-store
              spec:
                provider:
                  azurekv:
                    authType: ManagedIdentity
                    vaultUrl: https://devplatform-kv-fb11afr.vault.azure.net/
                    serviceAccountRef:
                      name: external-secrets  # This is the name of your Kubernetes Service Account
                      namespace: external-secrets  # This is the namespace where the service account exists
          
          externalSecrets:
            - apiVersion: external-secrets.io/v1beta1
              kind: ExternalSecret
              metadata:
                name: cloudflare-secret
                namespace: argocd
              spec:
                refreshInterval: "15m"
                secretStoreRef:
                  name: azure-keyvault-store
                  kind: ClusterSecretStore
                target:
                  name: cloudflare-api-token
                data:
                - secretKey: api-token
                  remoteRef:
                    key: cloudflare-api-token
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true