apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: csi-secrets-store-provider-azure
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    targetRevision: 1.4.1
    helm:
      valueFiles:
        - ../apps/secrets-csi/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Azure Key Vault Provider for Secrets Store CSI Driver"