apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-xrds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # After Crossplane and providers are installed
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    path: config/crossplane/xrds
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true