apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
      chart: csi-secrets-store-provider-azure
      targetRevision: 1.4.1
    - repoURL: https://github.com/sanveld/gitops.git
      path: config/secrets-csi
      targetRevision: "main"
  helm:
    valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Azure Key Vault Provider for Secrets Store CSI Driver"