apiVersion: v2
name: grafana
description: A Helm chart for Grafana monitoring and visualization platform
version: 1.0.0
type: application
appVersion: "9.5.3"
dependencies:
  - name: grafana
    version: 6.58.8
    repository: https://grafana.github.io/helm-charts