apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "6f9b8ca3-3c62-497b-b856-b2f1f644c7da"
    keyvaultName: "kv-devplatform-ya566l7"  # Replace with your Key Vault name if different
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: cloudflare-api-token
          objectType: secret
          objectAlias: cloudflare-api-token
    tenantId: "${AZURE_TENANT_ID}"  # This will be populated from the pod's environment
  secretObjects:
    - secretName: cloudflare-api-token
      type: Opaque
      data:
        - objectName: cloudflare-api-token
          key: CF_API_TOKEN