provider: cloudflare

cloudflare:
  apiTokenSecretRef:
    name: cloudflare-api-token
    key: api-token

# provider:
#   name: cloudflare

# env:
#   - name: CF_API_TOKEN
#     valueFrom:
#       secretKeyRef:
#         name: cloudflare-api-token
#         key: api-token

source:
  - ingress

domainFilters:
  - everythingascode.dev

policy: sync

txtOwnerId: "aks-cluster-externaldns-cf"