provider: cloudflare

cloudflare:
  apiToken: ${CF_API_TOKEN}
  secretName: cloudflare-api-token

# Specify domain filter to limit to your domain
domainFilters:
  - everythingascode.dev

extraEnvVars:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        # Must match spec.secretObjects.secretName in SecretProviderClass
        name: external-dns-cloudflare-secret
        # Must match spec.secretObjects.data.key in SecretProviderClass
        key: CF_API_TOKEN

txtOwnerId: "aks-cluster"
policy: sync
registry: txt
interval: "1m"
sources:
  - service
  - ingress

txtPrefix: "external-dns-"

rbac:
  create: true

serviceAccount:
  create: true
  name: external-dns

podSecurityContext:
  fsGroup: 65534

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi