apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-secretstore
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://devplatform-kv-fb11afr.vault.azure.net/" # Replace with your actual Key Vault URL in production (e.g., https://mykeyvault.vault.azure.net)
      serviceAccountRef:
        name: external-secrets