apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-keyvault-secretstore
    kind: SecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api-token