replicaCount: 1

# Enable Azure Key Vault provider
provider:
  azurekv:
    enabled: true

# Service account for ESO
serviceAccount:
  create: true
  name: "external-secrets"
  annotations:
    azure.workload.identity/client-id: "ad5768e3-3e19-48be-aaec-05391395f77d" # Replace with your User Assigned Managed Identity client ID in production

extraVolumeMounts:
  - name: azure-identity-token
    mountPath: /var/run/secrets/azure/tokens
    readOnly: true

extraVolumes:
  - name: azure-identity-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          path: azure-identity-token
          expirationSeconds: 86400
          audience: api://AzureADTokenExchange

# Set pod identity config for azure auth
podLabels:
  azure.workload.identity/use: "true"

# Log level
logging:
  level: info

# Add custom resources to be deployed with the chart
customResources:
  secretStores:
    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: azure-keyvault-secretstore
        namespace: external-secrets
      spec:
        provider:
          azurekv:
            authType: WorkloadIdentity
            vaultUrl: "https://devplatform-kv-fb11afr.vault.azure.net/" 
            serviceAccountRef:
              name: external-secrets

  externalSecrets:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: cloudflare-api-token
        namespace: external-secrets
      spec:
        refreshInterval: "1h"
        secretStoreRef:
          name: azure-keyvault-secretstore
          kind: SecretStore
        target:
          name: cloudflare-api-token
          creationPolicy: Owner
        data:
        - secretKey: api-token
          remoteRef:
            key: cloudflare-api-token