apiVersion: v2
name: prometheus-values
description: Values for Prometheus
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
- name: prometheus
  version: 15.18.0
  repository: https://prometheus-community.github.io/helm-charts