provider: cloudflare
cloudflare:
  # Using CSI driver to fetch API token from Azure Key Vault
  apiToken: "${api-token}"  # This will reference the mounted secret
  proxied: false  # Set to true if you want Cloudflare to proxy the traffic
  keyVault:
    # Use the name from Terraform output: $(terraform -chdir=../../terraform/00-static-resources output -raw key_vault_name)
    name: "kv-devplatform-d815qx2"  # This should match your static Key Vault name
    tenantId: "${tenantId}"      # Will be populated from AKS identity

domainFilters:
  - everythingascode.dev

txtOwnerId: "aks-cluster"  # Unique identifier for this External-DNS instance

policy: sync  # sync, upsert-only, or create-only
registry: txt  # Use TXT records to track ownership

interval: "1m"

sources:
  - service
  - ingress

txtPrefix: "external-dns-"

# Configure volume mounts for CSI driver
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true

extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: external-dns-cloudflare
      nodePublishSecretRef:
        name: cloudflare-api-token

# Use environment variable with mounted secret
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

rbac:
  create: true

serviceAccount:
  create: true
  name: external-dns

podSecurityContext:
  fsGroup: 65534

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Set to true if you have Prometheus Operator

logLevel: info
logFormat: text