apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-secretstore
  namespace: external-secrets
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: "https://kv-devplatform-2.vault.azure.net/"
      identityId: "e64fcf36-d0fa-4b18-9056-bce3aac74657"