apiVersion: v2
name: external-secrets-wrapper
description: A wrapper chart for deploying the External Secrets Operator

type: application

# Version of this wrapper chart
version: 0.1.0

# Version of the application being deployed (optional, can match dependency)
appVersion: "0.9.9" # Or the version you intend to use

dependencies:
  - name: external-secrets
    version: "0.9.9" # Specify the version of the external-secrets chart you want
    repository: "https://charts.external-secrets.io"
    # alias: external-secrets # Optional: if you want to refer to it differently in values.yaml
