apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.example.com"  # Replace with your Vault server URL
      path: "secret"  # Default KV path, adjust as needed
      version: "v2"  # KV engine version (v1 or v2)
      auth:
        # Choose one of the authentication methods below:
        
        # Option 1: Kubernetes auth method (commented out)
        # kubernetes:
        #   mountPath: "kubernetes"  # Default Vault Kubernetes auth mount path
        #   role: "external-secrets"  # Role configured in Vault for your application
        #   serviceAccountRef:
        #     name: "external-secrets"  # Service account used by External Secrets
        #     namespace: "external-secrets"  # Namespace where service account exists
        
        # Option 2: Token auth method
        token:
          secretRef:
            name: "vault-token"
            namespace: "external-secrets"
            key: "token"
        
        # Option 3: AppRole auth method (commented out)
        # appRole:
        #   path: "approle"  # AppRole path in Vault
        #   roleId: "role-id"  # Or use roleIdSecretRef for a secret reference
        #   secretRef:
        #     name: "vault-approle"
        #     namespace: "external-secrets"
        #     key: "secret-id"
