apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
data:
  token: "YOUR_BASE64_ENCODED_VAULT_TOKEN" # Replace with your actual token encoded in base64
