apiVersion: v2
name: nginx-ingress
description: A Helm chart for Nginx Ingress Controller
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: ingress-nginx
    version: "*"  # Use latest version
    repository: https://kubernetes.github.io/ingress-nginx
