apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xazurevms.compute.devplatform0.com
spec:
  group: compute.devplatform0.com
  names:
    kind: XAzureVM
    plural: xazurevms
  claimNames:
    kind: AzureVM
    plural: azurevms
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "Name for the VM"
              vmSize:
                type: string
                description: "Size of the VM"
                default: "small"
                enum:
                  - small
                  - medium
                  - large
              location:
                type: string
                description: "Azure region where resources will be deployed"
                default: "westeurope"
              sshPublicKey:
                type: string
                description: "SSH public key for VM access"
            required:
            - name
            - vmSize
            - sshPublicKey