apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: acme-middleware
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: 443
    # Don't redirect ACME challenge paths
    regex: "^(?!/.well-known/acme-challenge/)"
