# Simple Traefik configuration for testing
# No cert-manager or external-dns integration

# Enable CRD installation
installCRDs: true

deployment:
  kind: Deployment

# Enable Kubernetes Ingress provider
providers:
  kubernetesIngress:
    enabled: true
    namespaces: []
    publishedService:
      enabled: true

# Basic service configuration
service:
  enabled: true
  type: LoadBalancer

# Dashboard and API
ingressRoute:
  dashboard:
    enabled: true

# Ports configuration
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"