service:
  enabled: true
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    ingressClass: traefik-external
    namespaces: [] # Empty array means all namespaces

  kubernetesIngress:
    enabled: true

additionalArguments:
  - "--api.insecure=true" # Exposes the dashboard on port 8080
ports:
  traefik:
    expose: true
    exposedPort: 8080
    port: 8080
