installCRDS: true
service:
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true

# Enable TLS support
ssl:
  enabled: true
  
# Middleware for HTTPS redirection with exception for ACME challenges
additionalArguments:
  - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
  - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
  - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
  - "--entrypoints.websecure.http.tls.certResolver=le"
  
ports:
  web:
    port: 8000
    expose: {}  # Changed from boolean to empty object
    exposedPort: 80
  websecure:
    port: 8443
    expose: {}  # Changed from boolean to empty object
    exposedPort: 443

# Resource limits
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "300m"
    memory: "150Mi"
