service:
  enabled: true
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    ingressClass: traefik-external
    namespaces: []  # Empty array means all namespaces

  kubernetesIngress:
    enabled: true