apiVersion: v2
name: cert-manager
description: A Helm chart wrapper for cert-manager for GitOps management
type: application
version: 0.1.0
appVersion: "v1.17.1"
dependencies:
  - name: cert-manager
    version: v1.17.1
    repository: https://charts.jetstack.io
