apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sjveldhuizen@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod

    # Enable the DNS-01 challenge provider with Cloudflare
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
      # - http01:
      #     ingress:
      #       class: traefik
