installCRDs: true

cainjector:
  enabled: true

startupapicheck:
  enabled: true
  timeout: 5m

# Configure webhook for single-node AKS cluster
webhook:
  # Disable node affinity for single-node clusters
  affinity: {}

extraVolumes:
  - name: secrets-store-csi-cloudflare
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "cert-manager-cloudflare"
extraVolumeMounts:
  - name: secrets-store-csi-cloudflare
    mountPath: "/mnt/secrets-store/cloudflare"
    readOnly: true

# Resource limits for cert-manager
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "300Mi"

# Security context settings
securityContext:
  enabled: true
  fsGroup: 1001
