installCRDs: true

cainjector:
  enabled: true

startupapicheck:
  enabled: true
  timeout: 5m

# Configure webhook for single-node AKS cluster
webhook:
  # Disable node affinity for single-node clusters
  affinity: {}

resources:
  requests:
    cpu: "100m"
    memory: "150Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"