installCRDs: false

cainjector:
  enabled: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: type
            operator: In
            values:
            - virtual-machine

startupapicheck:
  enabled: true
  timeout: 5m
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: type
            operator: In
            values:
            - virtual-machine

# Global affinity for cert-manager controller
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: type
          operator: In
          values:
          - virtual-machine

resources:
  requests:
    cpu: "100m"
    memory: "150Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"