installCRDs: true

# Resource limits for cert-manager
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "300Mi"

# Enable webhook for validation
webhook:
  enabled: true

# Enable Prometheus metrics
prometheus:
  enabled: true
  servicemonitor:
    enabled: false

# Security context settings
securityContext:
  enabled: true
  fsGroup: 1001
