apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-builder-canvas
  namespace: cloud-builder-canvas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-builder-canvas
  template:
    metadata:
      labels:
        app: cloud-builder-canvas
    spec:
      containers:
      - name: cloud-builder-canvas
        image: ghcr.io/sanveld/cloud-builder-canvas:latest
        ports:
        - containerPort: 80