apiVersion: v1
kind: Service
metadata:
  name: cloud-builder-canvas-service
  namespace: cloud-builder-canvas
spec:
  type: ClusterIP
  selector:
    app: cloud-builder-canvas
  ports:
    - name: http
      port: 80 # Port the service listens on
      targetPort: 80 # Port the nginx container listens on
