apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: backstage
spec:
  secretName: backstage-tls
  issuerRef:
    name: letsencrypt-prod  # Adjust to match your cert-manager issuer name
    kind: ClusterIssuer     # or Issuer, depending on your setup
  dnsNames:
    - backstage.everythingascode.dev
