apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.0
      helm:
        valueFiles:
          - $values/config/cert-manager/values.yaml
    - repoURL: https://github.com/sanveld/gitops.git
      ref: values
      targetRevision: HEAD
    - repoURL: https://github.com/sanveld/gitops.git
      path: config/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Cert-manager for automatic SSL certificate management"
