apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    targetRevision: HEAD
    path: config/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
ignoreDifferences:
# Ignore the specific namespaceSelector fields within the webhook configurations
- group: admissionregistration.k8s.io
  kind: ValidatingWebhookConfiguration
  name: cert-manager-webhook # Check the exact name if different
  jsonPointers:
  - /webhooks/0/namespaceSelector/matchExpressions # Adjust index if needed
- group: admissionregistration.k8s.io
  kind: MutatingWebhookConfiguration
  name: cert-manager-webhook # Check the exact name if different
  jsonPointers:
  - /webhooks/0/namespaceSelector/matchExpressions # Adjust index if needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Cert-manager for automatic SSL certificate management"
