apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-builder-canvas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    targetRevision: HEAD
    path: config/cloud-builder-canvas
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-builder-canvas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
