apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/master
      targetRevision: 1.20.0-rc.0.41.g0c30ccb60
      chart: crossplane
      helm:
        valueFiles:
          - $values/config/crossplane/values.yaml
    - repoURL: https://github.com/sanveld/gitops.git
      ref: values
      targetRevision: HEAD
    - repoURL: https://github.com/sanveld/gitops.git
      path: config/crossplane
      targetRevision: HEAD
      directory:
        include: "azure-management-provider.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
