apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/depends-on: crossplane-providers
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    path: config/crossplane/provider-configs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true