apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-secretprovider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    path: config/crossplane
    targetRevision: HEAD
    directory:
      include: "secretproviderclass.yaml,crossplane-creds-provider.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "SecretProviderClass for Crossplane Azure credentials"
