apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: "1.16.1"

    helm:
      valuesObject:
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: api-token
        source:
          - ingress
        domainFilters:
          - everythingascode.dev
        policy: sync
        txtOwnerId: "aks-cluster-externaldns-cf"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "External DNS controller for managing Cloudflare DNS records"