apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.14.1
    - repoURL: https://github.com/sanveld/gitops.git
      path: config/external-dns
      targetRevision: "main"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  helm:
    valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "External DNS controller for managing Cloudflare DNS records"