apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-secretprovider
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sanveld/gitops.git
    path: config/external-dns
    targetRevision: HEAD
    directory:
      include: "secretproviderclass.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "SecretProviderClass for External DNS Cloudflare integration"
