apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 35.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  helm:
    values: |
      # installCRDS: true
      service:
        type: LoadBalancer
      providers:
        kubernetesCRD:
          enabled: true
      resources:
        requests:
          cpu: "100m"
          memory: "50Mi"
        limits:
          cpu: "300m"
          memory: "150Mi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: Description
      value: "Traefik Ingress Controller with External DNS and Cert Manager integration"