# letsencrypt-staging-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Email address used for ACME registration
    email: sjveldhuizen@gmail.com # <-- CHANGE THIS
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key
      name: letsencrypt-staging-account-key
    # Add a single challenge solver, HTTP01 using ingress-nginx
    solvers:
    - http01:
        ingress:
          class: nginx # Matches the default class for ingress-nginx helm chart