apiVersion: v1
kind: Service
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9093
      targetPort: web
      protocol: TCP 