apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9090
      targetPort: web
      protocol: TCP 