apiVersion: v1
kind: Pod
metadata:
  name: azure-secret-creator
  namespace: crossplane-system
spec:
  containers:
    - name: busybox
      image: busybox
      command:
        - "/bin/sleep"
        - "3600"
      volumeMounts:
        - name: azure-creds-volume
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: azure-creds-volume
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "crossplane-azure-creds"
