apiVersion: v1
kind: Pod
metadata:
  name: crossplane-creds-provider
  namespace: crossplane-system
spec:
  serviceAccountName: crossplane  # Make sure this matches Crossplane's service account
  containers:
    - name: credentials-sync
      image: bitnami/kubectl:latest
      command:
        - "/bin/sleep"
        - "infinity"
      volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "crossplane-azure-creds"
